---
title: "Experiment with CelebFaces"
author: "P. Cordero, M. Enciso, A. Mora, C. Rossi"
date: "11/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(devtools)
devtools::load_all("/Volumes/ImacUMA2019/Google Drive/Mi unidad/CooperativeFiltering")
library(knitr)
library(arules)
library(fcaR)
library(Matrix)
 

 library(tidyverse)
 library(pmml)
 library(sets)
 library(magrittr)
  # library("stringr")
# library(data.table)
# library(readxl)
# #library(readr)

 library(foreach)
 library(doParallel)
 library(doSNOW)
# library(foreach)

#read_chunk("R/main.R")


setwd("/Volumes/ImacUMA2019/Google Drive/Mi unidad/CooperativeFiltering")

FC <- read.csv ("datasets/list_attr_celeba.csv")
indicex <- FC==-1
FC[indicex] <- 0

colnames(FC)
filas <- rownames(FC)
FC1 <-as.data.frame(sapply(FC[,2:41], function(x) as.logical(x)))
#View(head(FC1))

my_support <- 0.0005
rule_param = list(
  supp = my_support,
  conf = 1,
  maxlen = 15
)
dt_experiment_sizes <- data.frame(execution=c(),
                                    experiment=c(),
                                    iteration=c(),
                                    sigma=c(),
                                    #closure=c(),
                                    attributes=c(),
                                    objects=c(), 
                                    closure=c())



```
 
 
 
```{r}
Rules <- apriori(FC1,parameter = rule_param)
name_file_rules <- "reglas_celebA.xml"



Rules <- Rules[!is.redundant(Rules)]
 
fc_movielens <- FormalContext$new(FC[,2:41])
fc_movielens$implications$add(Rules)
#fc_movielens$implications
#fc_movielens$implications$apply_rules(rules = c("composition",
#                                                "simplification"))

#Rules <- fc_movielens$implications$to_arules(quality = FALSE)

#write.PMML(Rules, file = name_file_rules)

num_execution <- 1
num_experiment <- 1
verbose <- FALSE

# n number of users
n_users=3
num_scales <- 4

number_executions_of_the_experiment <- 10

for (k in 1:number_executions_of_the_experiment){


  
    recommendation <- random_experiment_dataset(FC1,name_file_rules,
                                            n_users,num_scales,
                                            my_support, 
                                            num_execution,
                                            num_experiment, verbose )
    
    dt_experiment_sizes <- rbind(dt_experiment_sizes,recommendation$pref_sizes )
    num_experiment <- num_experiment +1

}
    dt_experiment_sizes

```
 
 